<?php
$parentBlock = $block->getParentBlock();
$_item = $parentBlock->getItem();
?>
<div data-mage-init='{"Nkdev_QuantityWidget/js/cart-quantity-widget": {}}'>
    <div class="quantity_input_wrapper">
        <div class="control custom-qty">
            <button class="decrease" type="button">-</button>
            <input
                class="input-text qty"
                data-role="cart-item-qty"
                data-validate="{required:true,'validate-greater-than-zero':true}"
                id="<?= $block->escapeHtml($_item->getSku()) ?>"
                name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                data-cart-item-size="4"
                title="<?= $block->escapeHtml(__('Qty')) ?>"
                type=" number"
                value="<?= $block->escapeHtmlAttr($parentBlock->getQty()) ?>"
            />
            <button class="increase" type="button">+</button>
        </div>
    </div>
    <span class="quantity_input__error-message"></span>
</div>