<?php
$parentBlock = $block->getParentBlock();
$_item = $parentBlock->getItem();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$checkoutSession = $objectManager->get('\Magento\Checkout\Model\Session');
$quoteId = $checkoutSession->getQuote()->getId();
?>
<div data-mage-init='{"Nkdev_QuantityWidget/js/quantity-widget": {}}'>
    <div class="quantity_input_wrapper">
        <button class="decrease" type="button">-</button>
        <input name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]" data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>" value="<?= /* @escapeNotVerified */ $parentBlock->getQty() ?>" type="number" size="4" title="<?= $block->escapeHtml(__('Qty')) ?>" class="input-text qty" data-validate="{required:true,'validate-greater-than-zero':true}" data-role="cart-item-qty" />
        <button class="increase" type="button">+</button>
    </div>
    <span class="quantity_input__error-message"></span>
</div>